### ISSUE TITLE
Configurable random choice between n options

### ISSUE THREAD

**Issue by metamatik** [django-waffle/django-waffle#114]
Hi James,

We have a use case that is not covered yet in waffle.
Basically, we have multiple providers and we want to be able to randomize them for a given user, with configurable odds.

Something like:
option1: 50%
option2: 30%
option3: 15%
option4: 5%

This choice would then be sticky for the user, so it seems to make sense to use the underlying mechanisms of waffle.

Do you think it would be interesting to have this feature in waffle?
If so, I might be able to convince my boss to work on a fork and eventually merge it back in your repo.

Let me know what you think :)

**Comment by jsocol** [comment]
Multi-valued samples are something I've always avoided in Waffle, because it complicates both implementation and how people think about using feature flags. Implementation of n-valued flags, and all the downstream assumptions it breaks, is my bigger concern, but I think pushing people into on/off values is a positive consequence.
