### ISSUE TITLE
Automatically create predefined flags, switches and samples

### ISSUE THREAD

**Issue by asyncee** [django-waffle/django-waffle#126]
Hello.
I think, the project should allow user to setup some default flags, switches and samples in settings, so those created automatically on application start.

Config may be in format (for example):

```
WAFFLE_DEFAULTS = {
    'flags': [
        {
            'name': flag_name,
            'active': True,
        },
        {
            'name': flag_name,
            'active': True,
        }    
    ],
     'switches': [... same ...]
}
```

So, i can configure predefined set of features i want to flip and they will be created automatically on every deployment.

**Comment by jsocol** [comment]
The point of waffle is largely to decouple feature flags from deployment. I know that it does a lot on top of that, but the underlying idea of feature flags is that features != deployments.

If this is just about autocreating flags, see #95 for an open pull req. If it's about configuring flags in the settings instead of the DB, I don't really feel that's worth pursuing.
