### ISSUE TITLE
Generic object flag support

### ISSUE THREAD

**Issue by cabello** [django-waffle/django-waffle#129]
I have a scenario where a flag is enable or disabled for a entire Company. How can I achieve that with waffle?

**Comment by jsocol** [comment]
This isn't really a well-formed idea. Flags operate on requests. It can operate on the `user` attribute of the request, or the `COOKIES` dict, but it's all tied to the request.

I'd suggest creating a group in the backend for each company and using that, since Flags support groups just fine.

A core rewrite might make this possible via extensions, as long as the request object has some reference to the company, but doing a GFK doesn't make sense.

**Comment by cabello** [comment]
Suppose I have public profile pages, Profile A has some beta feature enabled, Profile B doesn't. Anonymous users visiting these profiles should see them with correct features enabled and/or disabled. Is there a way to achieve that with Waffle?

Maybe writing a new middleware and template tags that calls Waffle functions based on the visited profile... I am not sure yet.

**Comment by jsocol** [comment]
This should be a different issue/pull req, because it's a different question.

I'd accept something along the lines of (this incomplete example):

```
class Flag(models.Model):
    # ...
    def is_enabled_for(self, user):
        if user in self.user_set():
            return True
        return any(user.groups() in self.group_set())
```

But there is a _massive_ caveat here which is that you **must** be using per-user or per-group flags for that to work. If you're relying on cookies and roll-out parts of Waffle, there is no mapping between a database user and flag, because it's cookie-based, it's tied to the browser. That is, under normal use, it's entirely possible for a human user to have a flag enabled but not to be able to know that from the database user.

At that point, I start to believe that it's the wrong way to do it. That's not what Waffle is for. Waffle is for feature deployments and roll-outs and AB tests.

I just went through a similar situation and my solution was that the "things that depend on the owner's state but not the viewer's state" shouldn't be done with Waffle at all.
