### ISSUE TITLE
testutils.py missing from tarball hosted on https://pypi.python.org/pypi/django-waffle

### ISSUE THREAD

**Issue by PhilipHauber** [django-waffle/django-waffle#147]
The python file testutils.py is missing from the tarball hosted on https://pypi.python.org/pypi/django-waffle. 
When doing an _python setup.py sdist_ manually this file is included. I did not check whether other files are missing, too. Maybe you could re-upload django-waffle 0.10.1 to make unittesting available again.

**Comment by jsocol** [comment]
[0.10.1](https://github.com/jsocol/django-waffle/milestones/0.10.1) doesn't include the integration testing tools, those are part of [0.11](https://github.com/jsocol/django-waffle/milestones/0.11).

It looks like there's a bunch of stuff there but it's not actually all that bad. If there is a separate [0.10.2](https://github.com/jsocol/django-waffle/milestones/0.10.2), the integration test tools will be part of it, since they're already in master.

**Comment by PhilipHauber** [comment]
Ok, thanks. I was just confused by the [0.10.1 documentation](http://waffle.readthedocs.org/en/latest/testing/automated.html#testing-automated)

**Comment by jsocol** [comment]
Oh, good catch. RTD normally defaults to "latest" so I've added the 0.10.1 tagged version and made it the default.
