### ISSUE TITLE
Keep sample return value the same per request

### ISSUE THREAD

**Issue by fdemmer** [django-waffle/django-waffle#176]
i'd like to use a "sample" to enable a new feature for only some users. then in rather messy existing code, i need to get the decision `True` or `False` in multiple places, eg in the view and then again in the template and maybe in another template included somewhere. so the idea is, maybe optionally attach/cache the initial decision, that the `sample_is_active` made on the `request`... bad idea?

**Comment by jsocol** [comment]
It sounds like you want a Flag, not a Sample. Flags [are consistent within a request](https://github.com/jsocol/django-waffle/blob/master/waffle/__init__.py#L95-L96). One of the constraints—by design—of samples is that they do not require any request-like-state. If you need it to be consistent everywhere outside of a request, you'll need to roll the dice once and pass around the result. Something like a global or thread-local to cache the value might help, if the code is too messy to be refactored to support that.

**Comment by fdemmer** [comment]
i am reluctant to comment again on a closed issue, but i did not want to email privately and can't find an alternative: 

my point with this idea was, that i still want **random distribution** of enabled/disabled, just consistent within a request. if i'd use a flag, i could enable the feature for everybody or by enabling it to trigger my own manual %-distribution of enable/disable distribution code, which i then attach to the request or a thread local (which, well, is what waffle was made for). so i was thinking in the direction of adding a thread local encapsulated in waffle, used by the `sample_is_active` call, or maybe having `sample_is_active` **optionally** take a `request` as argument and attach it there. again: completely optional.

i see that this breaks the principal of "only flag is request based" and understand that adding complexity does not weigh up demand, just wanted to clarify in case i was misunderstood or someone else has such a requirement.

**Comment by fdemmer** [comment]
woah. i just now realized flags also support percentages. is this new? :P 

sorry for the noise!
