### ISSUE TITLE
update jingo

### ISSUE THREAD

**Issue by jsocol** [django-waffle/django-waffle#179]
In django 1.8, `get_standard_processors` moved, and a few other things. as of https://github.com/jbalogh/jingo/pull/74, jingo supports these changes, but not in master yet. to fix [django1.8 tests](https://travis-ci.org/jsocol/django-waffle/jobs/60748561) and merge #159, we'll need to pick up the updated jingo

**Comment by willkg** [comment]
In Mozilla-land, all the projects I'm aware of are dropping Jingo and friends for django-jinja and other apps that are more actively maintained (plus not maintained by us) and are closer to vanilla Django.

I mention that because you seem to be doing all the work on Jingo lately, but if downloads on PyPI are much to go on, then Jingo probably has a pretty small user base. Might be worth ending that project as well as eventually dropping support in django-waffle for it.

**Comment by jsocol** [comment]
Well, it's still supported by waffle for today. If no one is using it there, I might start cowboying stuff in. We should absolutely do what we need to do to support django-jinja, if that's the way the wind is blowing, but I'm not dropping jingo just yet.

**Comment by jsocol** [comment]
Here's the route I'm trying right now: move from mutating the `jingo.env` directly to adding a legit Jinja extension that injects the globals. That should be compatible with any jinja2 template engine.

**Comment by willkg** [comment]
@rlr did a PR for fixing things to support django-jinja #167. It sounds like you want to go a different route (totally fine). I'm game for testing your changes with django-jinja if that helps.

**Comment by jsocol** [comment]
I feel like the jinja2 extension is the "right" way to do this. And it gives us broader support with less hacky stuff, especially [this whole set of comments](https://github.com/jsocol/django-waffle/pull/167/files#diff-fc8be72bf42266bd813ee2fdeec40a0bR39).

But, thanks for reminding me, this largely solves the "ugh testing" problem I just ran into.

**Comment by jsocol** [comment]
Closing this for #180 as well
