### ISSUE TITLE
error while rendering page without request context

### ISSUE THREAD

**Issue by timtan** [django-waffle/django-waffle#250]
while I use a flag with testing mode. 

and if I render a page without request context.

the error happen.

```
    def is_active(self, request):
        if not self.pk:
            return get_setting('FLAG_DEFAULT')

        if get_setting('OVERRIDE'):
            if self.name in request.GET:
                return request.GET[self.name] == '1'

        if self.everyone:
            return True
        elif self.everyone is False:
            return False

        if self.testing:  # Testing mode is on.
            tc = get_setting('TEST_COOKIE') % self.name
>           if tc in request.GET:
E           AttributeError: 'NoneType' object has no attribute 'GET'

```

**Comment by jsocol** [comment]
Flags require a request, that is fundamental to how they work. Switches and Samples do not, however—so they might be more appropriate for this use case?

If you're using a template in a test without a whole view (for example) or otherwise need to fake a request object during a test, the best way to use a [`RequestFactory`](https://docs.djangoproject.com/en/1.11/topics/testing/advanced/#the-request-factory) to generate one.

**Comment by timtan** [comment]
thanks for the quick response :)
