### ISSUE TITLE
Read all flags for a request

### ISSUE THREAD

**Issue by sburns** [django-waffle/django-waffle#257]
Hey thank you so much for waffle, it makes our feature-flagging so much more enjoyable.

If I want to deliver on/off status for _every_ flag on a site (e.g. to a SPA so it can opt users into purely front-end behavior or not), is there a better way to do it than...

```python
from waffle import flag_is_active
from waffle.models import Flag
flag_names = Flag.objects.values_list('name', flat=True)
flags = {flag_name: flag_is_active(request, flag_name) for flag_name in flag_names}
...
```

Or is there some easier method?

Again, many thanks for such a useful library!

**Comment by mwarkentin** [comment]
@sburns have you looked at the [waffle javascript support](https://waffle.readthedocs.io/en/v0.11/usage/javascript.html)?

**Comment by sburns** [comment]
We're using webpack to bundle our front-end and it's not necessarily fun to deal w/ global scripts. I could likely make it work but just hadn't gone down that road yet.

**Comment by jsocol** [comment]
There's a `.get_all()` method on Flags/Switches/Samples that will leverage the cache to make it a little faster, that's what `waffle.js` does internally: https://github.com/jsocol/django-waffle/blob/master/waffle/views.py#L21-L38

Ultimately you're not going to be able to bundle these into webpack, since they're not static, but depend on each request. There are a couple of options, [both documented](http://waffle.readthedocs.io/en/stable/usage/javascript.html): either using the provided view and route as a separate JS script, or loading in the template tag as an inline script element.

**Comment by sburns** [comment]
`*.get_all()` looks fantastic, I appreciate it!
