### ISSUE TITLE
How to reduce the number of network calls with switch_is_active

### ISSUE THREAD

**Issue by wsantos** [django-waffle/django-waffle#261]
We are having a situation where we need to call waffle inside a model property and this end up calling redis 400x times, do we have a plan to cache waffle calls in-mmeory locally ? so we don't need to do duplicated calls ?

**Comment by jsocol** [comment]
Which waffle method are you using?

**Comment by wsantos** [comment]
Here it is my snippet

```python
    def logo(self):
            if waffle.switch_is_active(
                    'USE-JPEG'):
                return jpeg
            return png
```

**Comment by jsocol** [comment]
Ah, switches, ok.

When you say you're making 400 calls to redis, what's the unit of rate? Is it 400 calls per request? Per second across several requests?

**Comment by wsantos** [comment]
It does 400 calls per request.

**Comment by jsocol** [comment]
Just to clarify from the title, Flags _do_ attach to the request to avoid re-lookups, but not just to avoid hitting the cache. They do it to ensure that their value is consistent throughout the request.

Switches don't require a request object, so they can't do that.

There are a couple of options:
1. Use a flag instead of a switch. Flags can be used as switches, with a simple boolean on/off. But they _require_ a request object, so they can't be used e.g. in celery or a cronjob, or other non-request contexts.
2. Save the switch state in a variable somewhere. Not only will it reduce lookups to the cache, it will guarantee that the switch state is consistent through a single request—otherwise it might change.

These will only help if you're looking up the same, or a small number of, switches multiple times. But if you're doing that, it feels like some kind of code smell to me. If you're not, and you have hundreds of switches, nothing is going to help, since each one will need to be checked at some point.

A very simple way to update that snippet to cache the result (assuming the object is created on each request) would be

```py
_logo = None
def logo(self):
    if not self._logo:
        if waffle.switch_is_active('USE-JPEG'):
            self._logo = jpeg
        else:
            self._logo = png
    return self._logo
```

Another way would be to store `self._use_jpeg = switch_is_active('USE-JPEG')`. Either way.

**Comment by wsantos** [comment]
Yeah you're right, the problems is actually the code and the flag is used to deep in the stack trace, I was trying to find a easy solution to it without a major refectory, thanks.

With that said are you open to a PR with a extra way to handle flags, i.e: Save them in a thread data cache ?, another change that I'd like to do to this approach is to have a `get_many` so we could pre load all of them in this "thread data".

**Comment by jsocol** [comment]
I'm not open to that PR, no. In-process caches are nearly impossible to invalidate correctly and simultaneously, which would lead to multiple flag values on different hosts at different times. Flags in particular (as opposed to switches or samples) shouldn't change within one request, but they already behave that way.

However if you do want to pursue that, there is a `get_all()` method for all 3 types. [`Flag.get_all()`](https://github.com/jsocol/django-waffle/blob/master/waffle/models.py#L59) will leverage whatever out-of-process cache you have, if any. You could combine that with each model's `is_active()` method to avoid the out-of-process cache lookups.

I'm going close out this issue, since it seems like it's resolved. Thanks for the question!
