### ISSUE TITLE
How to do multiple states?

### ISSUE THREAD

**Issue by oppianmatt** [django-waffle/django-waffle#279]
Looks like currently the states are boolean, either on or off. How would you do one that did A, B or C ? A multi choice field like waffle feature.

Currently doing it with booleans leads to state explosion

**Comment by charleswhchan** [comment]
Motivation and Use Cases (for reference): http://blog.launchdarkly.com/tag/multivariate-feature-flags/

**Comment by jsocol** [comment]
Flags, Switches and Samples are all boolean, yeah. I think this would need to be another type (or two), like `Variant`, with a slightly different API, since it's not `is_active()` but something more like `get_variation()` or similar.

I'm not sure how to do rules other than percentages for this. Is it valuable to say that authenticated users always get variation A? It seems like it.

Maybe `Variant` is the main way we access these, but there's another `Variation` (or `VariantVariation` so the names are more distinct) model for each variation, which could have some rules attached to it? That could become ambiguous, though.

It's probably OK to do just one type and not worry about the "no request context" case, or consider a separate API to rely only on percentages. This should probably wait for #1 first to be able to leverage the same deterministic-but-random bucketing.

Anyway, open to suggestions on what it might look like to implement this. Probably better to hash it out here a little bit before someone writes code, though.
