### ISSUE TITLE
Option to bypass cache

### ISSUE THREAD

**Issue by romulorosa** [django-waffle/django-waffle#350]
Hi, 

Sorry if this feature is already available but I couldn't find in the documentation.
I am facing some difficulties regarding the cache on Django 2.2. By default Django uses a local cache `django.core.cache.backends.locmem.LocMemCache` which holds the information in memory. Turns out that if we have a separate process (Kafka consumer, Celery worker or even a python shell started) which has already cached the switch information on the `LocMemCache`, this cache will not be properly flushed once you change the switch value. 
For instance, if my Kafka consumer has already retrieved the switch value and then I change this value on admin's panel, the cached value will still keeping the old value.

I was wondering if would not be interesting to have a way to bypass the cache and basically allow Waffle to hit the database everytime. The only solution to solve this was actually setting a DummyCache as my default cache, but I wouldn't like to disable the cache widely.

**Comment by clintonb** [comment]
The different caches on different machines is one of the main reasons users should opt for a central cache server rather than local memory caches.

If you don’t want to implement a cache server, your simplest option today is to setup a dummy cache with a name different than `default` and pass that name to Waffle via settings. This will enable you to disable caching solely for Waffle.

**Comment by romulorosa** [comment]
Hi Clinton,

Thaks for replying. That's totally works for me. Again, thanks for the
insight!

Em ter, 22 de out de 2019 17:48, Clinton Blackburn <notifications@github.com>
escreveu:

**Comment by msscaroso** [comment]
Hi  @romulorosa @clintonb 
I had an issue where multiple tests running concurrently were reading a not expected value from `waffle.switch_is_active`. The expected value was defined by `override_switch`. Some of the tests were supposed to find a `False` valued switch and some a `True` valued switch.

As far as I investigated, the issue was due a race condition with the feature flag cache. 
Each test thread has a specific database, but only one cache instance exists in the entire suite. Thus the cache instance was shared among the tests and then they were non isolated in that perspective.


The solution was to configure a dummy cache backend in django, as suggested by @clintonb , and configure Waffle to use it in the test environment.

```
CACHES["dummy_cache"] = {"BACKEND": "django.core.cache.backends.dummy.DummyCache"}

WAFFLE_CACHE_NAME = "dummy_cache"
```
(Needless to say, this is test env only config)

I was working with `pytest` and [`xdist`](https://github.com/pytest-dev/pytest-xdist) to run them concurrently.

**Comment by msscaroso** [comment]
btw Thank you for the insight!
