### ISSUE TITLE
'wafflescan' command to find waffle conditionals in codebase

### ISSUE THREAD

**Issue by groovecoder** [django-waffle/django-waffle#75]
manage.py wafflescan should show all the switches, flags, or samples that are checked in the codebase.

**Comment by jsocol** [comment]
This involves either regex or ast parsing Python, Django, and Jinja2 templates (the latter without being able to tell them apart ahead of time). This scares me.

The goal is just to know all the places waffle conditionals are used, right? There've got to be less nightmarish ways of addressing that.

**Comment by simonluijk** [comment]
```
grep waffle -Ir .
```

Works well on my code base. It finds all the load statements at the top of django templates. So at least you know which file to look in. From the examples it should also work with Jinja2 templates.

**Comment by lmorchard** [comment]
My $0.02:
- What might be interesting is, upon the first attempt to inspect a previously unknown waffle flag/switch, write a row with default values to the DB. That way, the system kind of self-documents, at least minimally with exposed admin items.
- Something I like about [Constance](https://github.com/comoga/django-constance), is that it requires a structure in `settings.py` that declares & describes all runtime settings. I kind of wish waffle supported some similar kind of checked-into-code declaration of waffle things.

**Comment by jsocol** [comment]
> Something I like about Constance, is that it requires a structure in settings.py that declares & describes all runtime settings. I kind of wish waffle supported some similar kind of checked-into-code declaration of waffle things.

I've always eschewed that intentionally because it was something I particularly disliked about django-feature-flipper. The data structure for switches and samples is relatively simple, but for flags it's big and complex and fragile.

**Comment by jsocol** [comment]
I'm closing this out. @lmorchard, if you want to go to bat for the settings approach, I'm all for it in dedicated issue. I'm open to convincing, just hesitant.

**Comment by tobych** [comment]
James, the JSON file in django-feature-flipper was important to the project I was working on because we wanted to deploy and have switches and flags created with all the right names and descriptions when we deployed, without having to do anything manually. I'm now at RECON Dynamics, where we use Waffle instead now and deploy to VMs, staging servers and production and need to have all the Waffle content consistent across them all. To that we use some code I wrote that does something similar to what django-feature-flipper did. I mentioned this to the Seattle Django group a couple of weeks ago when I did my first ever talk - on Waffle! - and it seemed to make sense to people. Anyway it reads a JSON (should be YAML really) file and adds any switches/flags it doesn't find in the database, updates any descriptions that have changed, and complains if there switches/flags in the database it doesn't see in the file. We use this all the time. Having it settings.py was all too much because - as you say - the data structure is pretty complicated for flags and I wanted to have some flexibility - perhaps to have a management command that dumps out the current settings to a file.

I know this only one solution to the problem. I'll ask RECON if I can let you have the source. Example JSON is in the slides for the talk, here: http://www.slideshare.net/tobych/waffle-talk-22102335

Matthew Scott (@gldnspud) is working with me at RECON too and we both love Waffle!
