### ISSUE TITLE
using waffle in settings.py

### ISSUE THREAD

**Issue by NadavK** [django-waffle/django-waffle#90]
Are there any caveats with using Waffle Switches to conditionally change settings in my project's settings.py?
For instance, is it required to restart the Django process for the changes to take effect?
And if a request is required, what is the best way to do this automatically?

Also on SO: http://stackoverflow.com/questions/19250316/using-waffle-to-toggle-settings-py

**Comment by tobych** [comment]
AFAIK that's not what Waffle's for. Although there are some settings it's safe to change at run-time, in general you should avoid this. I imagine the problem you have is really wanting to change settings at all at run-time, rather than not being able to do that with Waffle. What settings is it that you want to change?

**Comment by jsocol** [comment]
Toby's right, Waffle doesn't interact with settings that way. You can use something like [constance](https://github.com/comoga/django-constance) if you really need to tweak settings-like things. I'll put a more complete comment on SO.
