### ISSUE TITLE
percentage of users

### ISSUE THREAD

**Issue by marcosthejew** [django-waffle/django-waffle#93]
Hey, I needed to ask(I'm sorry if this is not the place but couldn't find any other) about the percentage field on the flags... for instance, If i have 100 users, 50 were shown the feature in the flag and 50 were not... is there a chance that a member of group B get the flag shown to them on a next try?
Thanks, Marcos

**Comment by marcosthejew** [comment]
...or that that the flag will not be shown to the A group on other tries?
Thanks,Marcos

**Comment by jsocol** [comment]
Only if the user doesn't have cookies enabled or are using a different/unsynced device or browser. When a flag is used, it sets a cookie to pin a given user to a given on/off state for that flag. The cookie is set if-and-only-if the flag is set based on the random dice role. E.g. if the flag is on because the user is a superuser, or their user ID is in the flag's user_id set, there's no cookie. Cookies are set to expire according to the `WAFFLE_MAX_AGE` setting, which defaults to 30 days.

There are a couple of caveats. The big one is if the flag is in "[rollout mode](http://waffle.readthedocs.org/en/latest/usage.html#rollout-mode)". In that case the "off" cookies are session cookies, and the "on" cookies are persistent.

The other is that a given user, even signed in, may see different flag values on different devices or browsers, unless they sync cookies somehow. That's an open issue (#1, which should tell you how little effort I've made to fix it) but such is the nature of cookies.

**Comment by jsocol** [comment]
Hope that helps, if not, feel free to reopen with follow-up questions.
